"""
router_api.py — CAIR Phase 2: FastAPI HTTP wrapper

What this file does:
  Wraps the existing CAIR Python library in a web server.
  After running this file, any app (browser, curl, another service) can
  call CAIR over HTTP instead of importing it as a Python module.

  Three endpoints (Step 1 = first two only):
    GET  /health         → is the server alive? what's the cache age?
    POST /route          → get a routing decision (no actual LLM call)
    POST /route-and-call → routing decision + real LLM response (Step 2)

How to start the server:
  cd "AI Safety/sa1-carbon-inference-router"
  uvicorn router_api:app --reload --port 8000

Then open in browser:
  http://localhost:8000/docs   ← interactive API docs (auto-generated by FastAPI)
  http://localhost:8000/health ← live health check

How FastAPI works (one paragraph):
  FastAPI is a Python library that turns your functions into HTTP endpoints.
  You decorate a function with @app.get("/health") and FastAPI handles all
  the HTTP machinery (parsing requests, validating JSON, sending responses).
  It also auto-generates an interactive docs page (/docs) so you can test
  every endpoint from a browser without writing any frontend code.
"""

import os
import time
import asyncio
from typing import Optional

# ── FastAPI imports ──────────────────────────────────────────────────────────
# FastAPI   = the web framework (creates the app object)
# HTTPException = lets us return structured error responses (e.g. 400, 500)
# BaseModel = Pydantic model — defines what request/response JSON looks like
# Field     = lets us add descriptions and defaults to Pydantic fields
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

# ── Anthropic client — used by /route-and-call to make the real LLM call ────
import anthropic

# ── Your existing CAIR modules ───────────────────────────────────────────────
# Nothing in these modules changes. FastAPI just calls them on your behalf.
from dotenv import load_dotenv
import yaml
from pathlib import Path

from complexity_scorer import score as complexity_score
from carbon_feed import get_carbon_multi, _cache as carbon_cache, CACHE_TTL_SECONDS
from routing_engine import route as cair_route
from budget_ledger import get_budget_status, log_emission, _ensure_table as ensure_ledger
from logger import init_db, log_decision


# ---------------------------------------------------------------------------
# Load environment + config
# ---------------------------------------------------------------------------

load_dotenv()

ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")
ELECTRICITY_MAPS_API_KEY = os.getenv("ELECTRICITY_MAPS_API_KEY") or None

# Read budget caps from the same YAML the rest of CAIR uses
def _load_budget_caps() -> tuple[float, float]:
    registry_path = Path(__file__).parent / "model_registry.yaml"
    try:
        data = yaml.safe_load(registry_path.read_text())
        caps = data.get("carbon_budget", {})
        return caps.get("daily_gCO2", 500.0), caps.get("monthly_gCO2", 12000.0)
    except Exception:
        return 500.0, 12000.0

DAILY_CAP, MONTHLY_CAP = _load_budget_caps()

# Collect all unique zones from all models so we can fetch carbon for them all
def _all_zones() -> list[str]:
    registry_path = Path(__file__).parent / "model_registry.yaml"
    try:
        data = yaml.safe_load(registry_path.read_text())
        seen, zones = set(), []
        for model in data.get("models", []):
            for z in model.get("preferred_regions", []):
                if z not in seen:
                    seen.add(z)
                    zones.append(z)
        return zones
    except Exception:
        return ["US-EAST", "EU-WEST"]

ALL_ZONES = _all_zones()


# ---------------------------------------------------------------------------
# Create the FastAPI app
# ---------------------------------------------------------------------------
# This one line creates the web server object.
# title, description, version appear on the /docs page automatically.

app = FastAPI(
    title="CAIR — Carbon-aware Inference Router",
    description=(
        "Routes LLM inference requests to the optimal model based on "
        "task complexity, grid carbon intensity, and latency SLA. "
        "POST /route for a routing decision. POST /route-and-call to also get "
        "the actual LLM response from the selected model."
    ),
    version="2.0.0",
)


# ---------------------------------------------------------------------------
# Startup: initialise databases
# ---------------------------------------------------------------------------
# @app.on_event("startup") runs once when uvicorn first starts the server.
# We use it to make sure the SQLite tables exist before any requests arrive.

@app.on_event("startup")
async def on_startup():
    init_db()        # creates routing_log.sqlite table if missing
    ensure_ledger()  # creates carbon_ledger table if missing


# ---------------------------------------------------------------------------
# Request and response models (Pydantic)
# ---------------------------------------------------------------------------
# BaseModel is what makes FastAPI's automatic validation work.
#
# When you POST to /route, FastAPI reads your JSON body and checks it
# against RouteRequest. If "task" is missing → automatic 422 error with
# a clear message. If latency_sla_ms is wrong type → same thing.
# You write zero validation code yourself.

class RouteRequest(BaseModel):
    task: str = Field(
        ...,                        # "..." means this field is required
        description="The task or prompt text you want to route to an LLM.",
        examples=["What is the capital of France?",
                  "Summarise this contract and flag any indemnity clauses."]
    )
    latency_sla_ms: Optional[int] = Field(
        default=None,
        description="Optional latency budget in milliseconds. "
                    "If set, CAIR will downgrade to a faster model if needed.",
        examples=[500, 2000]
    )


class RouteResponse(BaseModel):
    """What /route returns — a routing decision with full reasoning."""
    model_id: str
    model_tier: str               # small | medium | large
    region: str                   # zone code, e.g. "US-EAST"
    complexity_score: float       # 0.0–1.0
    complexity_tier: str          # SIMPLE | MEDIUM | COMPLEX
    complexity_confidence: str    # HIGH (Claude scored) | LOW (heuristic fallback)
    complexity_reasoning: str     # human-readable explanation of the score
    carbon_intensity_gco2_per_kwh: float
    carbon_source: str            # live | cached | static_default
    estimated_carbon_gco2: float
    latency_sla_ms: Optional[int]
    budget_state: str             # NORMAL | TIGHTENING | RESTRICTED | CRITICAL
    budget_tier_ceiling: str      # max tier the budget allows right now
    routing_reason: str           # full step-by-step reasoning chain


class HealthResponse(BaseModel):
    """What /health returns."""
    status: str
    carbon_cache_zones: int       # how many zones are in the cache
    carbon_cache_age_seconds: Optional[float]  # age of the oldest zone in cache
    budget_state: str
    budget_remaining_pct: float
    anthropic_key_present: bool
    electricity_maps_key_present: bool


# ---------------------------------------------------------------------------
# GET /health
# ---------------------------------------------------------------------------
# The simplest endpoint — no request body, just returns server status.
#
# @app.get("/health") is a decorator. It tells FastAPI:
#   "When someone sends a GET request to /health, run this function."
# FastAPI calls the function, takes the return value, serialises it to JSON,
# and sends it back. You don't write any HTTP code — just return a dict or model.

@app.get("/health", response_model=HealthResponse, tags=["Monitoring"])
async def health():
    """
    Check server status, cache state, and budget.

    Call this first to confirm the server is running and to see how
    fresh the carbon intensity data is.
    """
    # Check cache age — find the oldest cached zone
    now = time.time()
    cache_age: Optional[float] = None
    if carbon_cache:
        oldest = min(now - r.timestamp for r in carbon_cache.values())
        cache_age = round(oldest, 1)

    # Get current budget state (reads from SQLite — never fails)
    try:
        budget = get_budget_status(DAILY_CAP, MONTHLY_CAP)
        b_state = budget["state"]
        b_remaining = round(budget["remaining_pct"] * 100, 1)
    except Exception:
        b_state = "UNKNOWN"
        b_remaining = 100.0

    return HealthResponse(
        status="ok",
        carbon_cache_zones=len(carbon_cache),
        carbon_cache_age_seconds=cache_age,
        budget_state=b_state,
        budget_remaining_pct=b_remaining,
        anthropic_key_present=bool(ANTHROPIC_API_KEY),
        electricity_maps_key_present=bool(ELECTRICITY_MAPS_API_KEY),
    )


# ---------------------------------------------------------------------------
# POST /route
# ---------------------------------------------------------------------------
# The main endpoint. Accepts a task + optional SLA, runs the full CAIR
# pipeline, and returns a routing decision — but does NOT call the LLM.
# This is useful for: testing routing logic, dashboards, or callers who
# will make the actual LLM call themselves.
#
# "async def" matters here: FastAPI is async-native. When this handler
# awaits carbon/complexity calls, FastAPI can serve other requests in
# parallel — it doesn't block waiting for the Electricity Maps API.

@app.post("/route", response_model=RouteResponse, tags=["Routing"])
async def route(request: RouteRequest):
    """
    Get a routing decision for a task.

    Runs the full 3-signal CAIR pipeline:
    1. Complexity scoring (Claude Haiku or heuristic fallback)
    2. Grid carbon intensity fetch (Electricity Maps API or static defaults)
    3. Budget enforcement (daily/monthly cap state)
    4. Routing decision (model + region + reasoning)

    Does NOT call the selected LLM. Use /route-and-call for that.
    """
    try:
        # ── Step 1: Score task complexity ────────────────────────────────────
        # "await" means: start this async function and wait for it to finish
        # before moving on. While we wait, FastAPI can handle other requests.
        complexity = await complexity_score(request.task, ANTHROPIC_API_KEY)

        # ── Step 2: Fetch carbon intensity for all model zones ───────────────
        # We fetch all zones in parallel (asyncio.gather inside get_carbon_multi)
        # so waiting for FR doesn't delay US-EAST.
        carbon_readings = await get_carbon_multi(ALL_ZONES, ELECTRICITY_MAPS_API_KEY)

        # ── Step 3: Get current budget state ─────────────────────────────────
        # Reads from SQLite — tells us if today's carbon budget is tight
        budget = get_budget_status(DAILY_CAP, MONTHLY_CAP)
        budget_state = budget["state"]
        tier_ceiling = budget["tier_ceiling"]

        # ── Step 4: Make the routing decision ────────────────────────────────
        # route() is synchronous — it's just arithmetic over in-memory data.
        # We run it in a thread executor so it doesn't block the async event loop.
        decision = await asyncio.get_event_loop().run_in_executor(
            None,
            lambda: cair_route(
                complexity=complexity,
                carbon_readings=carbon_readings,
                sla_ms=request.latency_sla_ms,
                prompt=request.task,
                budget_ceiling=tier_ceiling,
                budget_state=budget_state,
            )
        )

        # ── Step 5: Log the decision ─────────────────────────────────────────
        # Non-blocking: if log fails, routing still succeeds (FP6 in PRD)
        log_decision(decision, request.task)
        log_emission(decision.estimated_carbon_gco2)

        # ── Step 6: Return the response ──────────────────────────────────────
        # FastAPI auto-serialises this to JSON. It validates against RouteResponse.
        return RouteResponse(
            model_id=decision.model_id,
            model_tier=decision.model_tier,
            region=decision.region,
            complexity_score=decision.complexity_score,
            complexity_tier=decision.complexity_tier,
            complexity_confidence=complexity.confidence,
            complexity_reasoning=complexity.reasoning,
            carbon_intensity_gco2_per_kwh=decision.carbon_intensity_gco2_per_kwh,
            carbon_source=decision.carbon_source,
            estimated_carbon_gco2=decision.estimated_carbon_gco2,
            latency_sla_ms=decision.latency_sla_ms,
            budget_state=decision.budget_state,
            budget_tier_ceiling=tier_ceiling,
            routing_reason=decision.routing_reason,
        )

    except Exception as e:
        # HTTPException tells FastAPI to return a structured error response
        # with the given HTTP status code and a JSON body {"detail": "..."}.
        # 503 = Service Unavailable — the server is up but something inside failed.
        raise HTTPException(status_code=503, detail=f"Routing failed: {str(e)}")


# ---------------------------------------------------------------------------
# POST /route-and-call
# ---------------------------------------------------------------------------
# Does everything /route does, then also calls the selected model with your
# task and returns the real LLM response alongside the routing decision.
#
# This is the endpoint you'd use in a real product:
#   Your app sends a task → CAIR picks the right model → CAIR calls that model
#   → your app gets both the answer AND a full audit trail of why that model
#   was chosen, how much carbon it cost, and what the budget state was.
#
# The key new concept here: after routing, we create an Anthropic client
# targeted at the specific model CAIR selected, call it, and return the text.

class RouteAndCallRequest(BaseModel):
    task: str = Field(
        ...,
        description="The task or prompt to route and send to the selected LLM.",
        examples=["What is the capital of France?",
                  "Summarise this contract and flag indemnity clauses."]
    )
    latency_sla_ms: Optional[int] = Field(
        default=None,
        description="Optional latency budget in ms. Routing will downgrade model if needed.",
        examples=[500, 2000]
    )
    system_prompt: Optional[str] = Field(
        default=None,
        description="Optional system prompt sent to the LLM alongside your task.",
        examples=["You are a helpful assistant. Be concise."]
    )
    max_tokens: int = Field(
        default=512,
        description="Maximum tokens in the LLM response. Increase for longer outputs.",
        examples=[256, 1024]
    )


class RouteAndCallResponse(BaseModel):
    """Routing decision + real LLM response in one payload."""
    # ── Routing fields (same as RouteResponse) ───────────────────────────────
    model_id: str
    model_tier: str
    region: str
    complexity_score: float
    complexity_tier: str
    complexity_confidence: str
    complexity_reasoning: str
    carbon_intensity_gco2_per_kwh: float
    carbon_source: str
    estimated_carbon_gco2: float
    latency_sla_ms: Optional[int]
    budget_state: str
    budget_tier_ceiling: str
    routing_reason: str
    # ── LLM response fields (new in this endpoint) ───────────────────────────
    llm_response: str             # the actual text the model returned
    llm_input_tokens: int         # tokens in your request (for cost/carbon tracking)
    llm_output_tokens: int        # tokens in the model's response
    llm_latency_ms: float         # how long the model call took in milliseconds


@app.post("/route-and-call", response_model=RouteAndCallResponse, tags=["Routing"])
async def route_and_call(request: RouteAndCallRequest):
    """
    Route a task AND call the selected LLM. Returns both the routing decision
    and the real model response in one JSON payload.

    How it works:
    1. Same 4-step routing pipeline as /route
    2. Creates an Anthropic client pointed at the selected model
    3. Calls that model with your task (+ optional system prompt)
    4. Returns everything: routing audit trail + LLM answer

    Use this when your app wants CAIR to handle both the routing AND the inference.
    """
    if not ANTHROPIC_API_KEY:
        raise HTTPException(
            status_code=503,
            detail="ANTHROPIC_API_KEY not set — cannot call LLM. Check your .env file."
        )

    try:
        # ── Steps 1–4: same routing pipeline as /route ───────────────────────
        complexity = await complexity_score(request.task, ANTHROPIC_API_KEY)
        carbon_readings = await get_carbon_multi(ALL_ZONES, ELECTRICITY_MAPS_API_KEY)
        budget = get_budget_status(DAILY_CAP, MONTHLY_CAP)
        budget_state = budget["state"]
        tier_ceiling = budget["tier_ceiling"]

        decision = await asyncio.get_event_loop().run_in_executor(
            None,
            lambda: cair_route(
                complexity=complexity,
                carbon_readings=carbon_readings,
                sla_ms=request.latency_sla_ms,
                prompt=request.task,
                budget_ceiling=tier_ceiling,
                budget_state=budget_state,
            )
        )

        # ── Step 5: Call the selected model ──────────────────────────────────
        # This is the new part vs /route.
        # We build the messages list and call the Anthropic API with the
        # exact model_id CAIR chose — not a hardcoded model, but the one
        # the router picked based on complexity + carbon + budget.
        #
        # AsyncAnthropic is the async version of the client — it integrates
        # with FastAPI's event loop so the server stays responsive while waiting
        # for the model to reply.

        llm_client = anthropic.AsyncAnthropic(api_key=ANTHROPIC_API_KEY)

        messages = [{"role": "user", "content": request.task}]

        call_kwargs = dict(
            model=decision.model_id,
            max_tokens=request.max_tokens,
            messages=messages,
        )
        if request.system_prompt:
            call_kwargs["system"] = request.system_prompt

        t0 = time.time()
        llm_result = await llm_client.messages.create(**call_kwargs)
        llm_latency_ms = round((time.time() - t0) * 1000, 1)

        # Extract the text response — content is a list of content blocks
        llm_text = llm_result.content[0].text if llm_result.content else ""

        # ── Step 6: Log decision + emission ──────────────────────────────────
        log_decision(decision, request.task)
        log_emission(decision.estimated_carbon_gco2)

        return RouteAndCallResponse(
            model_id=decision.model_id,
            model_tier=decision.model_tier,
            region=decision.region,
            complexity_score=decision.complexity_score,
            complexity_tier=decision.complexity_tier,
            complexity_confidence=complexity.confidence,
            complexity_reasoning=complexity.reasoning,
            carbon_intensity_gco2_per_kwh=decision.carbon_intensity_gco2_per_kwh,
            carbon_source=decision.carbon_source,
            estimated_carbon_gco2=decision.estimated_carbon_gco2,
            latency_sla_ms=decision.latency_sla_ms,
            budget_state=decision.budget_state,
            budget_tier_ceiling=tier_ceiling,
            routing_reason=decision.routing_reason,
            llm_response=llm_text,
            llm_input_tokens=llm_result.usage.input_tokens,
            llm_output_tokens=llm_result.usage.output_tokens,
            llm_latency_ms=llm_latency_ms,
        )

    except HTTPException:
        raise  # re-raise our own errors unchanged
    except Exception as e:
        raise HTTPException(status_code=503, detail=f"Route-and-call failed: {str(e)}")


# ---------------------------------------------------------------------------
# Smoke test — python router_api.py
# ---------------------------------------------------------------------------
# This doesn't start the server. It just verifies the module imports work.
# To start the server: uvicorn router_api:app --reload --port 8000

if __name__ == "__main__":
    print("router_api.py loaded successfully.")
    print(f"  Anthropic key present:         {'yes' if ANTHROPIC_API_KEY else 'NO — complexity scoring will use heuristic'}")
    print(f"  Electricity Maps key present:  {'yes' if ELECTRICITY_MAPS_API_KEY else 'no — carbon will use static defaults'}")
    print(f"  Budget caps:                   daily={DAILY_CAP}g  monthly={MONTHLY_CAP}g")
    print(f"  Zones to query:                {ALL_ZONES}")
    print()
    print("To start the server:")
    print('  uvicorn router_api:app --reload --port 8000')
    print()
    print("Then open: http://localhost:8000/docs")
